on:
  push:
    branches:
      - master
      - dev
  pull_request: {}

jobs:

  check-formatting:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: mrkkrp/ormolu-action@v8

  build:

    strategy:
      matrix:
        ghc: ['8.6', '9.4']
        text: ['1.2.5.0', '2.0']
      fail-fast: false

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3.2.0

      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.4
      
      - run: |
          echo "packages: ." > cabal.project
          echo "constraints:" >> cabal.project
          echo "  text == ${{ matrix.text }}" >> cabal.project
      - run: cabal update --enable-tests --enable-benchmarks
      - run: cabal freeze --enable-tests --enable-benchmarks

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - run: cabal build --enable-tests --enable-benchmarks
      - run: cabal test --enable-tests --enable-benchmarks
      
      - if: matrix.ghc != '8.4'
        run: cabal haddock --enable-tests --enable-benchmarks
